import React, { createContext, useContext, useState } from 'react';

export type Language = 'id' | 'en' | 'ja' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    'home': 'Beranda',
    'reels': 'Reels',
    'create': 'Buat',
    'leaderboard': 'Papan Peringkat',
    'profile': 'Profil',
    'admin': 'Admin',
    'search': 'Cari...',
    'logout': 'Keluar',
    'settings': 'Pengaturan',
    'language': 'Bahasa',
    'indonesian': 'Bahasa Indonesia',
    'english': 'English (Inggris)',
    'japanese': '日本語 (Jepang)',
    'chinese': '中文 (Cina)',
    'followers': 'Pengikut',
    'following': 'Mengikuti',
    'posts': 'Postingan',
    'nothing_here': 'Belum ada apa-apa di sini...',
    'moderate': 'Moderasi',
    'delete': 'Hapus',
    'edit_profile': 'Edit Profil',
    'save': 'Simpan',
    'cancel': 'Batal',
    'name': 'Nama',
    'bio': 'Bio',
    'banish': 'Blokir',
    'restore': 'Pulihkan',
    'comments': 'Komentar',
    'add_comment': 'Tambahkan komentar...',
    'post': 'Posting',
    'add_music': 'Tambah Musik',
    'done': 'Selesai',
    'skip': 'Lewati',
    'create_post': 'Buat Postingan',
    'what_on_mind': 'Apa yang Anda pikirkan?',
    'upload_photo': 'Unggah Foto',
    'upload_video': 'Unggah Video',
    'banned_msg': 'Akun Anda telah diblokir',
    'sign_in_google': 'Masuk dengan Google',
    'like': 'Suka',
    'dislike': 'Tidak Suka',
    'share': 'Bagikan',
    'copied': 'Tautan disalin ke papan klip!',
    'moderate_confirm': 'Moderasi postingan ini?',
    'delete_confirm': 'Hapus postingan ini?',
    'add_story': 'Tambah Cerita',
    'view_story': 'Lihat Cerita',
    'story_text_placeholder': 'Apa yang sedang terjadi?',
    'incoming_call': 'Panggilan Masuk...',
    'calling': 'Memanggil...',
    'ringing': 'Berdering...',
    'connected': 'Terhubung',
    'call_ended': 'Panggilan Berakhir',
    'end_call': 'Akhiri',
    'accept': 'Terima',
    'decline': 'Tolak',
    'audio_call': 'Suara',
    'video_call': 'Video',
    'collective_call': 'Grup',
    'start_voice_call': 'Panggilan Suara',
    'start_video_call': 'Panggilan Video',
    'join_call': 'Gabung Panggilan',
    'active_call_desc': 'Ada panggilan aktif di grup ini.',
    'live_stream': 'Live Stream',
    'go_live': 'Mulai Live',
    'live_video': 'Live Kamera Video',
    'live_screen': 'Live Berbagi Layar',
    'start_stream': 'Mulai Siaran Live',
    'stream_title_placeholder': 'Tulis judul siaran live Anda...',
    'end_stream': 'Akhiri Siaran Live',
    'viewers': 'Penonton',
    'live_chat': 'Obrolan Langsung',
    'send': 'Kirim',
    'stream_ended': 'Siaran Live Telah Berakhir',
    'switch_to_screen': 'Ganti ke Berbagi Layar',
    'switch_to_camera': 'Ganti ke Kamera',
    'active_live_streams': 'Siaran Live Saat Ini',
    'no_live_streams': 'Belum ada siaran live yang berlangsung',
    'live_leaderboard': 'Rangking Live Streamer',
    'post_leaderboard': 'Rangking Post',
    'top_streamers': 'Top Streamer Live',
    'top_likers': 'Pendukung Terbanyak',
    'live_rank_title': 'Papan Peringkat Live Vimos',
    'anon_match': 'Anonim Match',
    'anon_desc': 'Cari teman obrolan acak secara anonim. Identitas disembunyikan sampai Anda menekan Follow!',
    'anon_find': 'Cari Partner Anonim',
    'anon_searching': 'Mencari teman obrolan anonim...',
    'anon_cancel': 'Batal Cari',
    'anon_masked_name': 'Pengguna Anonim',
    'anon_follow_reveal': 'Follow & Ungkap Profil',
    'anon_leave': 'Akhiri Chat',
    'anon_next_match': 'Cari Partner Lain',
    'shop': 'Toko',
    'shop_desc': 'Dapatkan bingkai avatar, lencana VIP, dan efek unik!',
    'my_inventory': 'Inventaris Saya',
    'top_up': 'Isi Saldo Koin',
    'coins': 'Koin Vimos',
    'buy_now': 'Beli Sekarang',
    'equip': 'Gunakan',
    'unequip': 'Lepas',
    'owned': 'Dimiliki',
    'equipped': 'Terpasang',
    'all_items': 'Semua Item',
    'frames': 'Bingkai Profile',
    'badges': 'Lencana VIP',
    'gifts': 'Hadiah Live',
    'merch': 'Merchandise & Spesial',
    'top_up_success': 'Isi Saldo Berhasil!',
    'purchase_success': 'Pembelian Berhasil!',
    'alerts': 'Notif',
    'inbox': 'Pesan',
    'you': 'Profil',
    'found_shadows': 'Pengguna Ditemukan',
    'kings_broadcast': 'Pengumuman King',
    'captures': 'Tangkapan',
    'visual_echoes': 'Gema Visual',
    'add': 'Tambah',
    'legacy': 'Warisan',
    'no_captures': 'Belum ada tangkapan',
    'souls_following': 'Pengikut',
    'souls_followed': 'Mengikuti',
    'unfollow': 'Batal Ikuti',
    'follow_soul': 'Ikuti',
    'identity': 'Identitas',
    'vibe': 'Bio & Vibe',
    'save_changes': 'Simpan Perubahan',
    'no_email_data': 'Tidak ada data email',
    'visible_admin': 'Hanya terlihat oleh Admin King',
    'assign_role': 'Beri Peran',
    'ban_user': 'Blokir Pengguna',
    'restore_user': 'Pulihkan Pengguna',
    'banned_warning': 'Hati-hati, akun ini sedang dalam penyelidikan',
    'live_stream_title': 'Siaran Live Streaming',
    'live_stream_desc': 'Tonton siaran kamera & berbagi layar secara langsung, atau mulai panggung live Anda sendiri dalam satu sentuhan!',
    'active_streamers': 'Streamer Aktif',
    'all': 'Semua',
    'camera': 'Kamera',
    'screen': 'Layar',
    'search_stream_placeholder': 'Cari streamer atau judul siaran...',
    'live_now': 'Siaran Sedang Berlangsung',
    'results': 'Hasil',
    'watch_live': 'Masuk & Tonton Live',
    'watch': 'Tonton',
    'no_live_yet': 'Belum Ada Siaran Live',
    'no_live_desc': 'Saat ini belum ada streamer yang sedang siaran. Jadilah yang pertama memulai siaran kamera atau berbagi layar Anda sekarang!',
    'start_live_now': 'Mulai Live Sekarang',
    'community_streamers': 'Streamer & Komunitas Vimos',
    'marketplace_vimos': 'Marketplace Vimos',
    'shop_and_trade': 'TOKO & JUAL BELI',
    'shop_tagline': 'Buka toko Anda, pajang barang, & langsung bertransaksi lewat obrolan antar penjual & pembeli!',
    'explore_market': 'Jelajahi Pasar',
    'my_shop_title': 'Toko Saya',
    'trade_chat': 'Obrolan Jual Beli',
    'explore_items': 'Jelajahi Barang',
    'explore_shops': 'Jelajahi Toko',
    'search_market_placeholder': 'Cari barang, deskripsi, atau nama toko...',
    'search_shop_placeholder': 'Cari nama toko atau pemilik...',
    'all_categories': 'Semua Kategori',
    'cat_umum': 'Umum',
    'cat_fashion': 'Fashion',
    'cat_digital': 'Digital',
    'cat_aksesoris': 'Aksesoris',
    'cat_kuliner': 'Kuliner',
    'cat_jasa': 'Jasa',
    'cat_elektronik': 'Elektronik',
    'auth_tagline_login': 'Masuk ke dalam bayangan',
    'auth_tagline_register': 'Buat akun Anda sekarang',
    'auth_username_label': 'Username / Nama Pengguna',
    'auth_username_placeholder': 'Username unik Anda',
    'auth_email_label': 'Gmail / Alamat Email',
    'auth_email_placeholder': 'nama@gmail.com',
    'auth_password_label': 'Password / Kata Sandi',
    'auth_submit_login': 'Masuk ke Vimos',
    'auth_submit_register': 'Daftar Akun',
    'auth_switch_to_register': 'Belum punya akun? Daftar sekarang',
    'auth_switch_to_login': 'Sudah punya akun? Masuk',
    'auth_processing': 'Memproses...',
    'auth_change_language': 'Pilih Bahasa',
    'auth_error_username': 'Silakan masukkan Username Anda.',
    'auth_error_email_in_use': 'Email/Gmail ini sudah terdaftar. Silakan login.',
    'auth_error_weak_pass': 'Password terlalu pendek. Gunakan minimal 6 karakter.',
    'auth_error_invalid_email': 'Format Gmail/Email tidak valid.',
    'auth_error_general': 'Kesalahan akun. Periksa kembali email dan password Anda.'
  },
  en: {
    'home': 'Home',
    'reels': 'Reels',
    'create': 'Create',
    'leaderboard': 'Leaderboard',
    'profile': 'Profile',
    'admin': 'Admin',
    'search': 'Search...',
    'logout': 'Logout',
    'settings': 'Settings',
    'language': 'Language',
    'indonesian': 'Indonesian',
    'english': 'English',
    'japanese': 'Japanese',
    'chinese': 'Chinese',
    'followers': 'Followers',
    'following': 'Following',
    'posts': 'Posts',
    'nothing_here': 'Nothing here in Orbit...',
    'moderate': 'Moderate',
    'delete': 'Delete',
    'edit_profile': 'Edit Profile',
    'save': 'Save',
    'cancel': 'Cancel',
    'name': 'Name',
    'bio': 'Bio',
    'banish': 'Banish',
    'restore': 'Restore',
    'comments': 'Comments',
    'add_comment': 'Add a comment...',
    'post': 'Post',
    'add_music': 'Add Music',
    'done': 'Done',
    'skip': 'Skip',
    'create_post': 'Create Post',
    'what_on_mind': 'What\'s on your mind?',
    'upload_photo': 'Upload Photo',
    'upload_video': 'Upload Video',
    'banned_msg': 'Your soul has been exiled from Vimos.',
    'sign_in_google': 'Sign In with Google',
    'like': 'Like',
    'dislike': 'Dislike',
    'share': 'Share',
    'copied': 'Link copied to clipboard!',
    'moderate_confirm': 'Moderate this memory?',
    'delete_confirm': 'Are you sure you want to delete this post?',
    'add_story': 'Add Story',
    'view_story': 'View Story',
    'story_text_placeholder': 'What\'s happening?',
    'incoming_call': 'Incoming Call...',
    'calling': 'Calling...',
    'ringing': 'Ringing...',
    'connected': 'Connected',
    'call_ended': 'Call Ended',
    'end_call': 'End',
    'accept': 'Accept',
    'decline': 'Decline',
    'audio_call': 'Voice',
    'video_call': 'Video',
    'collective_call': 'Group',
    'start_voice_call': 'Voice Call',
    'start_video_call': 'Video Call',
    'join_call': 'Join Call',
    'active_call_desc': 'There is an active call in this collective.',
    'live_stream': 'Live Stream',
    'go_live': 'Go Live',
    'live_video': 'Live Camera Video',
    'live_screen': 'Live Screen Share',
    'start_stream': 'Start Live Stream',
    'stream_title_placeholder': 'Enter live stream title...',
    'end_stream': 'End Live Stream',
    'viewers': 'Viewers',
    'live_chat': 'Live Chat',
    'send': 'Send',
    'stream_ended': 'Live Stream Has Ended',
    'switch_to_screen': 'Switch to Screen Share',
    'switch_to_camera': 'Switch to Camera',
    'active_live_streams': 'Active Live Streams',
    'no_live_streams': 'No active live streams right now',
    'live_leaderboard': 'Live Streamer Ranking',
    'post_leaderboard': 'Post Ranking',
    'top_streamers': 'Top Live Streamers',
    'top_likers': 'Top Supporters',
    'live_rank_title': 'Vimos Live Leaderboard',
    'anon_match': 'Anonymous Match',
    'anon_desc': 'Search for random chat partners anonymously. Identity hidden until you hit Follow!',
    'anon_find': 'Find Anonymous Partner',
    'anon_searching': 'Searching for anonymous chat partner...',
    'anon_cancel': 'Cancel Search',
    'anon_masked_name': 'Anonymous User',
    'anon_follow_reveal': 'Follow & Reveal Profile',
    'anon_leave': 'End Chat',
    'anon_next_match': 'Find Next Partner',
    'shop': 'Shop',
    'shop_desc': 'Unlock exclusive avatar frames, VIP badges, and unique perks!',
    'my_inventory': 'My Inventory',
    'top_up': 'Top Up Coins',
    'coins': 'Vimos Coins',
    'buy_now': 'Buy Now',
    'equip': 'Equip',
    'unequip': 'Unequip',
    'owned': 'Owned',
    'equipped': 'Equipped',
    'all_items': 'All Items',
    'frames': 'Profile Frames',
    'badges': 'VIP Badges',
    'gifts': 'Live Gifts',
    'merch': 'Merchandise & Specials',
    'top_up_success': 'Top Up Successful!',
    'purchase_success': 'Purchase Successful!',
    'alerts': 'Alerts',
    'inbox': 'Inbox',
    'you': 'You',
    'found_shadows': 'Found Users',
    'kings_broadcast': 'King\'s Broadcast',
    'captures': 'Captures',
    'visual_echoes': 'Visual Echoes',
    'add': 'Add',
    'legacy': 'Legacy',
    'no_captures': 'No captures found',
    'souls_following': 'Souls Following',
    'souls_followed': 'Souls Followed',
    'unfollow': 'Unfollow',
    'follow_soul': 'Follow',
    'identity': 'Identity',
    'vibe': 'Bio & Vibe',
    'save_changes': 'Save Changes',
    'no_email_data': 'No email data',
    'visible_admin': 'Visible only to Admin King',
    'assign_role': 'Assign Role',
    'ban_user': 'Ban User',
    'restore_user': 'Restore User',
    'banned_warning': 'Caution, this account is under investigation',
    'live_stream_title': 'Live Streaming',
    'live_stream_desc': 'Watch camera & screen share live streams, or launch your own live stage in one tap!',
    'active_streamers': 'Active Streamers',
    'all': 'All',
    'camera': 'Camera',
    'screen': 'Screen',
    'search_stream_placeholder': 'Search streamers or stream title...',
    'live_now': 'Live Now',
    'results': 'Results',
    'watch_live': 'Watch Live Stream',
    'watch': 'Watch',
    'no_live_yet': 'No Live Streams Yet',
    'no_live_desc': 'There are currently no active streamers. Be the first to start your camera or screen share broadcast now!',
    'start_live_now': 'Start Live Now',
    'community_streamers': 'Vimos Streamers & Community',
    'marketplace_vimos': 'Vimos Marketplace',
    'shop_and_trade': 'SHOP & TRADE',
    'shop_tagline': 'Open your store, showcase items, & trade directly via buyer-seller chat!',
    'explore_market': 'Explore Market',
    'my_shop_title': 'My Shop',
    'trade_chat': 'Trade Chat',
    'explore_items': 'Explore Items',
    'explore_shops': 'Explore Shops',
    'search_market_placeholder': 'Search items, description, or shop name...',
    'search_shop_placeholder': 'Search shop name or owner...',
    'all_categories': 'All Categories',
    'cat_umum': 'General',
    'cat_fashion': 'Fashion',
    'cat_digital': 'Digital',
    'cat_aksesoris': 'Accessories',
    'cat_kuliner': 'Culinary',
    'cat_jasa': 'Services',
    'cat_elektronik': 'Electronics',
    'auth_tagline_login': 'Enter the Orbit',
    'auth_tagline_register': 'Create your account now',
    'auth_username_label': 'Username / Display Name',
    'auth_username_placeholder': 'Your unique username',
    'auth_email_label': 'Gmail / Email Address',
    'auth_email_placeholder': 'name@gmail.com',
    'auth_password_label': 'Password',
    'auth_submit_login': 'Enter Vimos',
    'auth_submit_register': 'Create Account',
    'auth_switch_to_register': "Don't have an account? Sign up now",
    'auth_switch_to_login': 'Already have an account? Sign in',
    'auth_processing': 'Processing...',
    'auth_change_language': 'Select Language',
    'auth_error_username': 'Please enter your username.',
    'auth_error_email_in_use': 'This email is already in use. Please log in.',
    'auth_error_weak_pass': 'Password is too weak. Must be at least 6 characters.',
    'auth_error_invalid_email': 'Invalid email format.',
    'auth_error_general': 'Account error. Please verify your email and password.'
  },
  ja: {
    'home': 'ホーム',
    'reels': 'リール',
    'create': '作成',
    'leaderboard': 'ランキング',
    'profile': 'プロフィール',
    'admin': '管理者',
    'search': '検索...',
    'logout': 'ログアウト',
    'settings': '設定',
    'language': '言語',
    'indonesian': 'インドネシア語',
    'english': '英語',
    'japanese': '日本語',
    'chinese': '中国語',
    'followers': 'フォロワー',
    'following': 'フォロー中',
    'posts': '投稿',
    'nothing_here': 'ここにはまだ何もありません...',
    'moderate': 'モデレート',
    'delete': '削除',
    'edit_profile': 'プロフィール編集',
    'save': '保存',
    'cancel': 'キャンセル',
    'name': '名前',
    'bio': '自己紹介',
    'banish': 'BANする',
    'restore': '復元',
    'comments': 'コメント',
    'add_comment': 'コメントを追加...',
    'post': '投稿',
    'add_music': '音楽を追加',
    'done': '完了',
    'skip': 'スキップ',
    'create_post': '投稿を作成',
    'what_on_mind': '今なにしてる？',
    'upload_photo': '写真をアップロード',
    'upload_video': '動画をアップロード',
    'banned_msg': 'あなたのアカウントは停止されています。',
    'sign_in_google': 'Googleでログイン',
    'like': 'いいね',
    'dislike': '低評価',
    'share': '共有',
    'copied': 'リンクをクリップボードにコピーしました！',
    'moderate_confirm': 'この投稿をモデレートしますか？',
    'delete_confirm': 'この投稿を削除してもよろしいですか？',
    'add_story': 'ストーリーを追加',
    'view_story': 'ストーリーを見る',
    'story_text_placeholder': '今何が起きてる？',
    'incoming_call': '着信中...',
    'calling': '発信中...',
    'ringing': '呼び出し中...',
    'connected': '接続済み',
    'call_ended': '通話終了',
    'end_call': '終了',
    'accept': '応答',
    'decline': '拒否',
    'audio_call': '音声',
    'video_call': 'ビデオ',
    'collective_call': 'グループ',
    'start_voice_call': '音声通話を開始',
    'start_video_call': 'ビデオ通話を開始',
    'join_call': '通話に参加',
    'active_call_desc': 'このグループでアクティブな通話があります。',
    'live_stream': 'ライブ配信',
    'go_live': 'ライブを開始',
    'live_video': 'カメラ配信',
    'live_screen': '画面共有配信',
    'start_stream': '配信を開始',
    'stream_title_placeholder': '配信タイトルを入力...',
    'end_stream': '配信を終了',
    'viewers': '視聴者',
    'live_chat': 'ライブチャット',
    'send': '送信',
    'stream_ended': 'ライブ配信が終了しました',
    'switch_to_screen': '画面共有に切替',
    'switch_to_camera': 'カメラに切替',
    'active_live_streams': '配信中のライブ',
    'no_live_streams': '現在配信中のライブはありません',
    'live_leaderboard': 'ライブ配信者ランキング',
    'post_leaderboard': '投稿ランキング',
    'top_streamers': 'トップ配信者',
    'top_likers': 'トップサポーター',
    'live_rank_title': 'Vimosライブランキング',
    'anon_match': '匿名マッチ',
    'anon_desc': '匿名でランダムチャット相手を探します。フォローするまで正体は隠されます！',
    'anon_find': '匿名パートナーを探す',
    'anon_searching': '匿名パートナーを検索中...',
    'anon_cancel': '検索をキャンセル',
    'anon_masked_name': '匿名ユーザー',
    'anon_follow_reveal': 'フォローしてプロフィール公開',
    'anon_leave': 'チャットを終了',
    'anon_next_match': '次のパートナーを探す',
    'shop': 'ショップ',
    'shop_desc': 'アバターフレーム、VIPバッジ、特別特典を解放しよう！',
    'my_inventory': 'マイインベントリ',
    'top_up': 'コインチャージ',
    'coins': 'Vimosコイン',
    'buy_now': '今すぐ購入',
    'equip': '装備',
    'unequip': '外す',
    'owned': '所持済み',
    'equipped': '装備中',
    'all_items': 'すべてのアイテム',
    'frames': 'プロフィールフレーム',
    'badges': 'VIPバッジ',
    'gifts': 'ライブギフト',
    'merch': 'グッズ＆スペシャル',
    'top_up_success': 'チャージ成功！',
    'purchase_success': '購入成功！',
    'alerts': '通知',
    'inbox': 'メッセージ',
    'you': 'マイページ',
    'found_shadows': '見つかったユーザー',
    'kings_broadcast': 'キングの放送',
    'captures': 'キャプチャ',
    'visual_echoes': 'ビジュアルエコー',
    'add': '追加',
    'legacy': 'レガシー',
    'no_captures': 'キャプチャが見つかりません',
    'souls_following': 'フォロワー',
    'souls_followed': 'フォロー中',
    'unfollow': 'フォロー解除',
    'follow_soul': 'フォロー',
    'identity': '身元',
    'vibe': '自己紹介',
    'save_changes': '変更を保存',
    'no_email_data': 'メールデータなし',
    'visible_admin': '管理者のみに表示',
    'assign_role': '役職を割り当て',
    'ban_user': 'ユーザーをBAN',
    'restore_user': 'ユーザーを復元',
    'banned_warning': '警告: このアカウントは調査中です',
    'live_stream_title': 'ライブ配信',
    'live_stream_desc': 'カメラや画面共有のライブ配信を視聴したり、ワンタップで自分のライブステージを開始できます！',
    'active_streamers': '配信中のストリーマー',
    'all': 'すべて',
    'camera': 'カメラ',
    'screen': '画面',
    'search_stream_placeholder': '配信者や配信タイトルを検索...',
    'live_now': '現在配信中',
    'results': '件',
    'watch_live': '入室してライブを視聴',
    'watch': '視聴',
    'no_live_yet': 'ライブ配信はまだありません',
    'no_live_desc': '現在配信中のストリーマーはいません。今すぐカメラや画面共有の配信を一番乗りで始めましょう！',
    'start_live_now': '今すぐ配信を開始',
    'community_streamers': 'Vimosストリーマー＆コミュニティ',
    'marketplace_vimos': 'Vimosマーケットプレイス',
    'shop_and_trade': 'ショップ ＆ 売買',
    'shop_tagline': 'ショップを開設し、商品を掲載して、売り手と買い手のチャットで直接取引しましょう！',
    'explore_market': '市場を探索',
    'my_shop_title': 'マイショップ',
    'trade_chat': '売買チャット',
    'explore_items': '商品を検索',
    'explore_shops': 'ショップを検索',
    'search_market_placeholder': '商品、説明、ショップ名を検索...',
    'search_shop_placeholder': 'ショップ名やオーナーを検索...',
    'all_categories': 'すべてのカテゴリー',
    'cat_umum': '一般',
    'cat_fashion': 'ファッション',
    'cat_digital': 'デジタル',
    'cat_aksesoris': 'アクセサリー',
    'cat_kuliner': 'グルメ',
    'cat_jasa': 'サービス',
    'cat_elektronik': '家電・電子機器',
    'auth_tagline_login': '影の世界へ足を踏み入れる',
    'auth_tagline_register': '今すぐアカウントを作成',
    'auth_username_label': 'ユーザー名 / 表示名',
    'auth_username_placeholder': 'あなた固有のユーザー名',
    'auth_email_label': 'Gmail / メールアドレス',
    'auth_email_placeholder': 'name@gmail.com',
    'auth_password_label': 'パスワード',
    'auth_submit_login': 'Vimosに入る',
    'auth_submit_register': 'アカウント登録',
    'auth_switch_to_register': 'アカウントをお持ちでないですか？ 新規登録',
    'auth_switch_to_login': '既にアカウントをお持ちですか？ ログイン',
    'auth_processing': '処理中...',
    'auth_change_language': '言語を選択',
    'auth_error_username': 'ユーザー名を入力してください。',
    'auth_error_email_in_use': 'このメールアドレスは既に登録されています。ログインしてください。',
    'auth_error_weak_pass': 'パスワードが短すぎます（6文字以上）。',
    'auth_error_invalid_email': 'メールアドレスの形式が正しくありません。',
    'auth_error_general': 'アカウントエラーが発生しました。メールアドレスとパスワードを確認してください。'
  },
  zh: {
    'home': '首页',
    'reels': '短视频',
    'create': '创建',
    'leaderboard': '排行榜',
    'profile': '个人资料',
    'admin': '管理员',
    'search': '搜索...',
    'logout': '退出登录',
    'settings': '设置',
    'language': '语言',
    'indonesian': '印尼语',
    'english': '英语',
    'japanese': '日语',
    'chinese': '中文',
    'followers': '关注者',
    'following': '正在关注',
    'posts': '帖子',
    'nothing_here': '这里还没有内容...',
    'moderate': '审核',
    'delete': '删除',
    'edit_profile': '编辑资料',
    'save': '保存',
    'cancel': '取消',
    'name': '姓名',
    'bio': '个人简介',
    'banish': '封禁',
    'restore': '恢复',
    'comments': '评论',
    'add_comment': '添加评论...',
    'post': '发布',
    'add_music': '添加音乐',
    'done': '完成',
    'skip': '跳过',
    'create_post': '创建帖子',
    'what_on_mind': '你在想什么？',
    'upload_photo': '上传照片',
    'upload_video': '上传视频',
    'banned_msg': '您的账号已被封禁。',
    'sign_in_google': '使用Google登录',
    'like': '赞',
    'dislike': '不喜欢',
    'share': '分享',
    'copied': '链接已复制到剪贴板！',
    'moderate_confirm': '是否审核此帖子？',
    'delete_confirm': '确定要删除此帖子吗？',
    'add_story': '添加动态',
    'view_story': '查看动态',
    'story_text_placeholder': '正在发生什么？',
    'incoming_call': '来电...',
    'calling': '正在呼叫...',
    'ringing': '正在响铃...',
    'connected': '已连接',
    'call_ended': '通话结束',
    'end_call': '结束',
    'accept': '接听',
    'decline': '拒绝',
    'audio_call': '语音',
    'video_call': '视频',
    'collective_call': '群组',
    'start_voice_call': '发起语音通话',
    'start_video_call': '发起视频通话',
    'join_call': '加入通话',
    'active_call_desc': '该群组中有一个正在进行的通话。',
    'live_stream': '实时直播',
    'go_live': '开始直播',
    'live_video': '摄像头直播',
    'live_screen': '屏幕共享直播',
    'start_stream': '开始直播',
    'stream_title_placeholder': '输入直播标题...',
    'end_stream': '结束直播',
    'viewers': '观众',
    'live_chat': '实时聊天',
    'send': '发送',
    'stream_ended': '直播已结束',
    'switch_to_screen': '切换到屏幕共享',
    'switch_to_camera': '切换到摄像头',
    'active_live_streams': '当前直播',
    'no_live_streams': '暂时没有正在进行的直播',
    'live_leaderboard': '直播主播排行榜',
    'post_leaderboard': '帖子排行榜',
    'top_streamers': '热门主播',
    'top_likers': '最高支持者',
    'live_rank_title': 'Vimos直播排行榜',
    'anon_match': '匿名匹配',
    'anon_desc': '匿名寻找随机聊天伙伴。在点击关注之前身份将被隐藏！',
    'anon_find': '寻找匿名伙伴',
    'anon_searching': '正在寻找匿名伙伴...',
    'anon_cancel': '取消搜索',
    'anon_masked_name': '匿名用户',
    'anon_follow_reveal': '关注并解锁资料',
    'anon_leave': '结束聊天',
    'anon_next_match': '寻找下一个伙伴',
    'shop': '商城',
    'shop_desc': '解锁专属头像框、VIP徽章和独特特权！',
    'my_inventory': '我的库存',
    'top_up': '充值金币',
    'coins': 'Vimos金币',
    'buy_now': '立即购买',
    'equip': '装备',
    'unequip': '卸下',
    'owned': '已拥有',
    'equipped': '已装备',
    'all_items': '所有道具',
    'frames': '头像框',
    'badges': 'VIP徽章',
    'gifts': '直播礼物',
    'merch': '商品与特惠',
    'top_up_success': '充值成功！',
    'purchase_success': '购买成功！',
    'alerts': '通知',
    'inbox': '消息',
    'you': '我的',
    'found_shadows': '找到的用户',
    'kings_broadcast': '国王广播',
    'captures': '抓拍',
    'visual_echoes': '视觉回响',
    'add': '添加',
    'legacy': '遗留',
    'no_captures': '未找到抓拍',
    'souls_following': '关注者',
    'souls_followed': '正在关注',
    'unfollow': '取消关注',
    'follow_soul': '关注',
    'identity': '身份',
    'vibe': '个人简介',
    'save_changes': '保存更改',
    'no_email_data': '无邮箱数据',
    'visible_admin': '仅管理员可见',
    'assign_role': '分配角色',
    'ban_user': '封禁用户',
    'restore_user': '解封用户',
    'banned_warning': '警告：该账号正在接受调查',
    'live_stream_title': '实时直播',
    'live_stream_desc': '观看摄像头和屏幕共享直播，或一键开启您自己的直播舞台！',
    'active_streamers': '活跃主播',
    'all': '全部',
    'camera': '摄像头',
    'screen': '屏幕',
    'search_stream_placeholder': '搜索主播或直播标题...',
    'live_now': '正在直播',
    'results': '条结果',
    'watch_live': '进入观看直播',
    'watch': '观看',
    'no_live_yet': '暂无直播',
    'no_live_desc': '目前没有主播在直播。现在就成为第一个开启摄像头或屏幕共享直播的人吧！',
    'start_live_now': '立即开始直播',
    'community_streamers': 'Vimos主播与社区',
    'marketplace_vimos': 'Vimos 电子集市',
    'shop_and_trade': '商店与交易',
    'shop_tagline': '开一家您的店铺，展示商品，并通过买卖家沟通直接完成交易！',
    'explore_market': '浏览市场',
    'my_shop_title': '我的店铺',
    'trade_chat': '交易聊天',
    'explore_items': '浏览商品',
    'explore_shops': '浏览店铺',
    'search_market_placeholder': '搜索商品、描述或店铺名称...',
    'search_shop_placeholder': '搜索店铺名称或店主...',
    'all_categories': '全部分类',
    'cat_umum': '通用',
    'cat_fashion': '时装',
    'cat_digital': '数码',
    'cat_aksesoris': '饰品配件',
    'cat_kuliner': '美食',
    'cat_jasa': '服务',
    'cat_elektronik': '电子产品',
    'auth_tagline_login': '进入暗影世界',
    'auth_tagline_register': '立即创建您的账号',
    'auth_username_label': '用户名 / 昵称',
    'auth_username_placeholder': '您的唯一用户名',
    'auth_email_label': 'Gmail / 电子邮箱',
    'auth_email_placeholder': 'name@gmail.com',
    'auth_password_label': '密码',
    'auth_submit_login': '进入 Vimos',
    'auth_submit_register': '注册账号',
    'auth_switch_to_register': '还没有账号？立即注册',
    'auth_switch_to_login': '已有账号？登录',
    'auth_processing': '处理中...',
    'auth_change_language': '选择语言',
    'auth_error_username': '请输入您的用户名。',
    'auth_error_email_in_use': '此邮箱已被注册，请直接登录。',
    'auth_error_weak_pass': '密码太短（至少6个字符）。',
    'auth_error_invalid_email': '邮箱格式不正确。',
    'auth_error_general': '账号错误，请检查邮箱和密码。'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('vimos_language');
    return (saved === 'en' || saved === 'id' || saved === 'ja' || saved === 'zh') 
      ? (saved as Language) 
      : 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('vimos_language', lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['en']?.[key] || translations['id']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
